// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-1:6a58b6e0-aaf1-4a08-b01d-123f3c2e9713',
    'aws_cognito_region': 'ap-southeast-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'askjeeves-hosting-mobilehub-1085157943',
    'aws_content_delivery_bucket_region': 'ap-southeast-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1k7vf4uuns6af.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'e28162aa22074fe7ba053e9258ba4579',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'eee7e8aa-2ad7-402f-a41d-f90a7e23789a',
    'aws_project_name': 'ask-jeeves-2018-08-15-16-02-23',
    'aws_project_region': 'ap-southeast-1',
    'aws_resource_name_prefix': 'askjeeves-mobilehub-1085157943',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-1_T3TQPOGW3',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '4vngsks71qm65ujmuaei7kbfqm',
}

export default awsmobile;
